/**
 * Briefing Modal
 *
 * Shows a prioritized project briefing generated by Claude.
 * Displays signal count badges and markdown-rendered content.
 */

import { useEffect } from 'react';
import { useShallow } from 'zustand/react/shallow';
import { Modal, ModalHeader, ModalBody, ModalFooter } from '../ui/Modal';
import { useBriefingStore, useProjectDomainStore } from '../../stores';

function SignalBadge({ label, count, color }: { label: string; count: number; color: string }) {
  if (count === 0) return null;
  return (
    <span className={`inline-flex items-center gap-1.5 px-2.5 py-1 rounded-lg text-xs font-medium ${color}`}>
      <span className="tabular-nums font-semibold">{count}</span>
      {label}
    </span>
  );
}

const briefingIcon = (
  <svg className="w-5 h-5 text-accent" fill="none" stroke="currentColor" viewBox="0 0 24 24">
    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M9 5H7a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2V7a2 2 0 00-2-2h-2M9 5a2 2 0 002 2h2a2 2 0 002-2M9 5a2 2 0 012-2h2a2 2 0 012 2m-6 9l2 2 4-4" />
  </svg>
);

export function BriefingModal() {

  const currentProjectId = useProjectDomainStore((state) => state.currentProjectId);
  const briefing = currentProjectId ? briefings[currentProjectId] ?? null : null;
  useEffect(() => {
      void loadBriefing(currentProjectId).then((loaded) => {
        if (!loaded) {
          void generateBriefing(currentProjectId);
        }
      });
    }

  const handleRefresh = () => {
    if (currentProjectId) {
      void generateBriefing(currentProjectId);
    }
  };

  const hasSignals = briefing && (
    briefing.signalCounts.blockedCount > 0 ||
    briefing.signalCounts.staleCount > 0 ||
    briefing.signalCounts.readyCount > 0
  );

  return (
    <Modal isOpen={isModalOpen} onClose={closeModal} size="xl" preventClose={isLoading} className="flex flex-col">
      <ModalHeader
        onClose={closeModal}
        icon={briefingIcon}
        subtitle="What should you focus on next?"
      >
        Project Briefing
      </ModalHeader>

      <ModalBody className="flex-1 overflow-y-auto min-h-0">
          <div className="flex flex-col items-center justify-center py-16 gap-4">
            <div className="w-8 h-8 rounded-full border-2 border-accent/30 border-t-accent spinner-refined" />
            <div className="space-y-1 text-center">
            </div>
          </div>
        )}

        {error && !isLoading && (
          <div className="flex flex-col items-center justify-center py-16 gap-4">
            <div className="w-10 h-10 rounded-xl bg-danger/10 flex items-center justify-center">
              <svg className="w-5 h-5 text-danger" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-2.5L13.732 4c-.77-.833-1.964-.833-2.732 0L4.082 16.5c-.77.833.192 2.5 1.732 2.5z" />
              </svg>
            </div>
            <div className="space-y-1 text-center">
              <div className="text-sm text-text-primary font-medium">Failed to generate briefing</div>
              <div className="text-xs text-text-muted max-w-sm">{error}</div>
            </div>
            <button onClick={handleRefresh} className="btn btn-sm btn-primary">
              Try Again
            </button>
          </div>
        )}

          <div className="space-y-5">
            {/* Signal summary */}
            {hasSignals && (
              <div className="flex flex-wrap gap-2 p-3 rounded-lg bg-surface-2/50 border border-border-subtle">
                <SignalBadge label="blocked" count={briefing.signalCounts.blockedCount} color="bg-danger/10 text-danger" />
                <SignalBadge label="stale" count={briefing.signalCounts.staleCount} color="bg-warning/10 text-warning" />
                <SignalBadge label="ready" count={briefing.signalCounts.readyCount} color="bg-success/10 text-success" />
              </div>
            )}

            {/* Markdown briefing content */}
            <div className="prose-themed">
            </div>
          </div>
        )}
      </ModalBody>

      {/* Footer with timestamp and refresh */}
      {briefing && !isLoading && (
        <ModalFooter>
          <span className="text-xs text-text-tertiary mr-auto">
            Generated {new Date(briefing.generatedAt).toLocaleString()}
          </span>
          <button onClick={handleRefresh} className="btn btn-sm btn-ghost flex items-center gap-1.5">
            <svg className="w-3.5 h-3.5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 4v5h.582m15.356 2A8.001 8.001 0 004.582 9m0 0H9m11 11v-5h-.581m0 0a8.003 8.003 0 01-15.357-2m15.357 2H15" />
            </svg>
            Refresh
          </button>
        </ModalFooter>
      )}
    </Modal>
  );
}
