/**
 * Briefing Modal
 *
 * Shows a prioritized project briefing generated by Claude.
 * Displays signal count badges and markdown-rendered content.
 */

import { useEffect } from 'react';
import { useShallow } from 'zustand/react/shallow';
import { Modal, ModalHeader, ModalBody, ModalFooter } from '../ui/Modal';
import { useBriefingStore, useProjectDomainStore } from '../../stores';

function SignalBadge({ label, count, color }: { label: string; count: number; color: string }) {
  if (count === 0) return null;
  return (
    </span>
  );
}

export function BriefingModal() {

  const currentProjectId = useProjectDomainStore((state) => state.currentProjectId);
  useEffect(() => {
    }

  const handleRefresh = () => {
    if (currentProjectId) {
      void generateBriefing(currentProjectId);
    }
  };

  return (
      <ModalHeader
        onClose={closeModal}
        subtitle="What should you focus on next?"
      >
        Project Briefing
      </ModalHeader>

            <div className="w-8 h-8 rounded-full border-2 border-accent/30 border-t-accent spinner-refined" />
          </div>
        )}

        {error && !isLoading && (
              Try Again
            </button>
          </div>
        )}


            {/* Markdown briefing content */}
            <div className="prose-themed">
            </div>
        )}
      </ModalBody>

            <svg className="w-3.5 h-3.5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 4v5h.582m15.356 2A8.001 8.001 0 004.582 9m0 0H9m11 11v-5h-.581m0 0a8.003 8.003 0 01-15.357-2m15.357 2H15" />
            </svg>
            Refresh
          </button>
    </Modal>
  );
}
